### ISSUE TITLE
Howto include / extend / inject Jade components

### ISSUE THREAD

**Issue by ghost** [Grawl/guidelines#1]
Hi, 
I've read your guidelines and find them very useful. The only thing I don't understand is, whether to extend or include components?
And also mixin calls in components: Where do I have to extend or include the files? At the specific component, or in one of the layout files, or just in the page which I want to create?

Thanks in advance!

**Comment by Grawl** [comment]
Glad to be helpful.

I think that if you want to extend a component, you have to create new one using existing component code. It will be a new component.

If I understand you the right way, it will be something like this...

You have a component named `badge` to show an image in circle shape with label on it, and want to create user avatar using this code. So:

`badge.jade`

``` jade
mixin badge(image, labelText)
    .badge
        img(src=image)
        span.badge-label=labelText
```

Using this code, you can create user avatar, for example, without label:

`user-avatar.jade`

``` jade
mixin user_avatar(image)
    +badge(image)
```

And modify `badge.jade` to allow using it without label:

``` jade
mixin badge(image, labelText)
    .badge
        img(src=image)
        if labelText
            span.badge-label=labelText
```

**Comment by ghost** [comment]
Thank you for your explanation, but unfortunately I probably expressed myself a bit wrong.

What I want to know is, where do I have to write the extend/include calls?

do I have to include the badge.jade file into the user-avatar.jade?

```
user-avatar.jade
```

``` jade
    include badge
```

```
    mixin user_avatar(image)
        +badge(image)
```

Or do I have to write:

```
badge.jade
```

``` jade
extend user-avatar
```

```
mixin badge(image, labelText)
    .badge
        img(src=image)
        if labelText
            span.badge-label=labelText
```

**Comment by Grawl** [comment]
It's up to you I think. My idea is not to limit technology usage but to create a wireframe to build anything on it.

If you think that `extend` is better so `extend`.

`extend` !== `include` you have to know the difference

**Comment by Grawl** [comment]
I think that will be better to include all partials into the base one with something like [`gulp-inject`](https://github.com/klei/gulp-inject) instead of controlling this low level manually.
